name: CI/CD for Bookstore Web

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Run tests
      run: npm run test -- --run

    - name: Build application
      run: npm run build

    - name: Test build output
      run: |
        ls -la dist/
        [ -f dist/index.html ] && echo "Build successful" || exit 1

  docker:
    name: Build and Test Docker
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t bookstore-web:latest .

    - name: Test Docker container
      run: |
        docker run -d -p 3000:80 --name test-web bookstore-web:latest
        sleep 10
        
        docker ps | grep test-web
        
        curl -f http://localhost:3000/ || (docker logs test-web && exit 1)
        
        docker stop test-web
        docker rm test-web

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: [test, docker]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Vercel
      run: |
        echo "CI/CD passed! Ready for deployment to Vercel"
        echo "Add VERCEL_TOKEN and VERCEL_ORG_ID secrets to deploy automatically"